LogFile=/var/log/zabbix-server/zabbix_server.log
PidFile=/run/zabbix/zabbix_server.pid
DBName=zabbix
DBUser=zabbix
DBPassword=12345
Timeout=4
AlertScriptsPath=/etc/zabbix/alert.d/
FpingLocation=/usr/bin/fping
LogSlowQueries=3000
StatsAllowedIP=127.0.0.1
EnableGlobalScripts=0
Include=/etc/zabbix/zabbix_server.conf.d/*.conf